name = "pridle"

account_id = ""
workers_dev = true
route = "pridle.nozomoto.me/*"
main = "./worker/index.js"
compatibility_date = "2022-07-21"

[site]
bucket = "./public"

[build]
command = "npm run build:worker"
watch_dir = "build/index.js"
